const cities = [
  "New York, USA",
  "Los Angeles, USA",
  "Chicago, USA",
  "Houston, USA",
  "Miami, USA",
  "Toronto, Canada",
  "Vancouver, Canada",
  "London, United Kingdom",
  "Manchester, United Kingdom",
  "Birmingham, United Kingdom",
  "Paris, France",
  "Marseille, France",
  "Lyon, France",
  "Berlin, Germany",
  "Munich, Germany",
  "Hamburg, Germany",
  "Rome, Italy",
  "Milan, Italy",
  "Naples, Italy",
  "Madrid, Spain",
  "Barcelona, Spain",
  "Valencia, Spain",
  "Tokyo, Japan",
  "Osaka, Japan",
  "Yokohama, Japan",
  "Sydney, Australia",
  "Melbourne, Australia",
  "Brisbane, Australia",
  "Cairo, Egypt",
  "Alexandria, Egypt",
  "Giza, Egypt",
  "Rio de Janeiro, Brazil",
  "São Paulo, Brazil",
  "Brasília, Brazil",
  "Dubai, UAE",
  "Abu Dhabi, UAE",
  "Sharjah, UAE",
  "Moscow, Russia",
  "Saint Petersburg, Russia",
  "Novosibirsk, Russia",
  "Beijing, China",
  "Shanghai, China",
  "Guangzhou, China",
  "Mumbai, India",
  "Delhi, India",
  "Bangalore, India",
  "Seoul, South Korea",
  "Busan, South Korea",
  "Incheon, South Korea",
  "Mexico City, Mexico",
  "Guadalajara, Mexico",
  "Monterrey, Mexico",
  "Buenos Aires, Argentina",
  "Santiago, Chile",
  "Lima, Peru",
  "Bogotá, Colombia",
  "Montevideo, Uruguay",
  "Caracas, Venezuela",
  "Dublin, Ireland",
  "Edinburgh, United Kingdom",
  "Amsterdam, Netherlands",
  "Brussels, Belgium",
  "Zurich, Switzerland",
  "Vienna, Austria",
  "Athens, Greece",
  "Stockholm, Sweden",
  "Oslo, Norway",
  "Copenhagen, Denmark",
  "Helsinki, Finland",
  "Warsaw, Poland",
  "Prague, Czech Republic",
  "Budapest, Hungary",
  "Istanbul, Turkey",
  "Tel Aviv, Israel",
  "Jerusalem, Israel",
  "Cape Town, South Africa",
  "Johannesburg, South Africa",
  "Nairobi, Kenya",
  "Casablanca, Morocco",
  "Dubrovnik, Croatia",
  "Reykjavik, Iceland",
  "Auckland, New Zealand",
  "Wellington, New Zealand",
  "Manila, Philippines",
  "Bangkok, Thailand",
  "Singapore, Singapore",
  "Kuala Lumpur, Malaysia",
  "Jakarta, Indonesia",
  "Hanoi, Vietnam",
  "Havana, Cuba",
  "San Juan, Puerto Rico",
  "San Jose, Costa Rica",
  "Guatemala City, Guatemala",
  "San Salvador, El Salvador",
  "Agra, India",
  "Auckland, New Zealand",
  "Buenos Aires, Argentina",
  "Cairo, Egypt",
  "Cape Town, South Africa",
  "Dubai, UAE",
  "Edinburgh, United Kingdom",
  "Florence, Italy",
  "Goa, India",
  "Hanoi, Vietnam",
  "Istanbul, Turkey",
  "Jerusalem, Israel",
  "Kathmandu, Nepal",
  "Lima, Peru",
  "Marrakech, Morocco",
  "Nairobi, Kenya",
  "Oslo, Norway",
  "Perth, Australia",
  "Quebec City, Canada",
  "Rome, Italy",
  "Seoul, South Korea",
  "Taipei, Taiwan",
  "Ulaanbaatar, Mongolia",
  "Valletta, Malta",
  "Warsaw, Poland",
  "Xi'an, China",
  "Yerevan, Armenia",
  "Zagreb, Croatia",
  "Brisbane, Australia",
  "Copenhagen, Denmark",
  "Dakar, Senegal",
  "Eindhoven, Netherlands",
  "Fukuoka, Japan",
  "Guadalajara, Mexico",
  "Havana, Cuba",
  "Innsbruck, Austria",
  "Jerusalem, Israel",
  "Kiev, Ukraine",
  "Lisbon, Portugal",
  "Munich, Germany",
  "Naples, Italy",
  "Ottawa, Canada",
  "Pristina, Kosovo",
  "Quebec City, Canada",
  "Riyadh, Saudi Arabia",
  "Stockholm, Sweden",
  "Tallinn, Estonia",
  "Ushuaia, Argentina",
  "Valletta, Malta",
  "Wellington, New Zealand",
  "Xiamen, China",
  "Yerevan, Armenia",
  "Zurich, Switzerland",
  "Amsterdam, Netherlands",
  "Barcelona, Spain",
  "Copenhagen, Denmark",
  "Dublin, Ireland",
  "Edinburgh, United Kingdom",
  "Frankfurt, Germany",
  "Geneva, Switzerland",
  "Helsinki, Finland",
  "Istanbul, Turkey",
  "Jerusalem, Israel",
  "Krakow, Poland",
  "Lisbon, Portugal",
  "Munich, Germany",
  "Naples, Italy",
  "Oslo, Norway",
  "Prague, Czech Republic",
  "Rome, Italy",
  "Seoul, South Korea",
  "Tokyo, Japan",
  "Ulaanbaatar, Mongolia",
  "Vancouver, Canada",
  "Warsaw, Poland",
  "Xi'an, China",
  "Yerevan, Armenia",
  "Zurich, Switzerland",
  "Asuncion, Paraguay",
  "Baku, Azerbaijan",
  "Cartagena, Colombia",
  "Dar es Salaam, Tanzania",
  "Eilat, Israel",
  "Fukuoka, Japan",
  "Guayaquil, Ecuador",
  "Hobart, Australia",
  "Islamabad, Pakistan",
  "Johannesburg, South Africa",
  "Kuala Lumpur, Malaysia",
  "Lima, Peru",
  "Marrakech, Morocco",
  "Nagoya, Japan",
  "Ouarzazate, Morocco",
  "Phuket, Thailand",
  "Quito, Ecuador",
  "Recife, Brazil",
  "San Jose, Costa Rica",
  "Tashkent, Uzbekistan",
  "Ushuaia, Argentina",
  "Venice, Italy",
  "Windhoek, Namibia",
  "Xiamen, China",
  "Yogyakarta, Indonesia",
  "Zagreb, Croatia",
  "Cairo, Egypt",
  "Johannesburg, South Africa",
  "Lagos, Nigeria",
  "Nairobi, Kenya",
  "Accra, Ghana",
  "Casablanca, Morocco",
  "Dar es Salaam, Tanzania",
  "Addis Ababa, Ethiopia",
  "Kampala, Uganda",
  "Dakar, Senegal",
  "Abuja, Nigeria",
  "Maputo, Mozambique",
  "Kigali, Rwanda",
  "Tunis, Tunisia",
  "Harare, Zimbabwe",
  "Luanda, Angola",
  "Lusaka, Zambia",
  "Maseru, Lesotho",
  "Gaborone, Botswana",
  "Banjul, Gambia",
  "Bujumbura, Burundi",
  "Mbabane, Eswatini",
  "Victoria, Seychelles",
  "Moroni, Comoros",
  "Praia, Cape Verde",
  "Monrovia, Liberia",
  "Bangui, Central African Republic",
  "Asmara, Eritrea",
  "Nouakchott, Mauritania",
  "Dire Dawa, Ethiopia",
  "Mek'ele, Ethiopia",
  "Gondar, Ethiopia",
  "Bahir Dar, Ethiopia",
  "Jimma, Ethiopia",
  "Hawassa, Ethiopia",
  "Dessie, Ethiopia",
  "Arba Minch, Ethiopia",
  "Jijiga, Ethiopia",
  "Shashamane, Ethiopia",
  "Adama, Ethiopia",
  "Haramaya, Ethiopia",
  "Harar, Ethiopia",
  "Nekemte, Ethiopia",
  "Axum, Ethiopia",
  "Debre Markos, Ethiopia",
  "Woldiya, Ethiopia",
  "Dila, Ethiopia",
  "Gambela, Ethiopia",
  "Asosa, Ethiopia",
  "Shire, Ethiopia",
  "Nekemte, Ethiopia",
  "Dembi Dolo, Ethiopia",
  "Gode, Ethiopia",
  "Debre Tabor, Ethiopia",
  "Giyon, Ethiopia",
  "Awasa, Ethiopia",
  "Bonga, Ethiopia",
  "Harar, Ethiopia",
  "Bishoftu, Ethiopia",
  "Dilla, Ethiopia",
  "Bishoftu, Ethiopia",
  "Debre Birhan, Ethiopia",
  "Hosaena, Ethiopia",
  "Shashemene, Ethiopia",
  "Boditi, Ethiopia",
  "Debre Berhan, Ethiopia",
  "Dabat, Ethiopia",
  "Kombolcha, Ethiopia",
  "Debre Zeyit, Ethiopia",
  "Negele Borana, Ethiopia",
  "Ginir, Ethiopia",
  "Dese, Ethiopia",
  "Fiche, Ethiopia",
  "Adigrat, Ethiopia",
  "Butajira, Ethiopia",
  "Wondo Genet, Ethiopia",
  "Werota, Ethiopia",
  "Mizan Teferi, Ethiopia",
  "Sodo, Ethiopia",
  "Jinka, Ethiopia",
  "Bonga, Ethiopia",
  "Robe, Ethiopia",
  "Guder, Ethiopia",
  "Agaro, Ethiopia",
  "Bure, Ethiopia",
  "Wacca, Ethiopia",
  "Sekota, Ethiopia",
  "Lalibela, Ethiopia",
  "Konso, Ethiopia",
  "Gimbi, Ethiopia",
  "Bedele, Ethiopia",
  "Hagere Hiywet, Ethiopia",
  "Bichena, Ethiopia",
  "Bati, Ethiopia",
  "Ziway, Ethiopia",
  "Bonga, Ethiopia",
  "Debre Tabor, Ethiopia",
  "Gambela, Ethiopia",
  "Agaro, Ethiopia",
  "Bure, Ethiopia",
  "Wacca, Ethiopia",
  "Sekota, Ethiopia",
  "Lalibela, Ethiopia",
  "Konso, Ethiopia",
  "Gimbi, Ethiopia",
  "Bedele, Ethiopia",
  "Hagere Hiywet, Ethiopia",
  "Bichena, Ethiopia",
  "Bati, Ethiopia",
  "Ziway, Ethiopia",
  "Mota, Ethiopia",
  "Tepi, Ethiopia",
  "Goba, Ethiopia",
  "Bako, Ethiopia",
  "Assela, Ethiopia",
  "Mendi, Ethiopia",
  "Mizan-Aman, Ethiopia",
  "Asaita, Ethiopia",
  "Guraghe, Ethiopia",
  "Fiche, Ethiopia",
  "Tulu Bolo, Ethiopia",
  "Debre Zeyit, Ethiopia",
  "Yirga Alem, Ethiopia",
  "Gonder, Ethiopia",
  "Adwa, Ethiopia",
  "Azezo, Ethiopia",
  "Asbe Teferi, Ethiopia",
  "Bichena, Ethiopia",
  "Chiro, Ethiopia",
  "Finote Selam, Ethiopia",
  "Giyon, Ethiopia",
  "Kemise, Ethiopia",
  "Kibre Mengist, Ethiopia",
  "Mega, Ethiopia",
  "Nefas Mewcha, Ethiopia",
  "Shakiso, Ethiopia",
  "Sire, Ethiopia",
  // Feel free to add more cities or specific regions from Ethiopia
];

export default cities;
